# （四）async 与 await

## 1. MDN 文档

文档上讲的很清楚，建议阅读文档上的例子和解释。

- async 函数：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function
- await：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/await

## 2. async 函数

- 函数的返回值为 `promise` 对象
-  `promise` 对象的结果由 `async` 函数执行的返回值决定

## 3. await 表达式

- await右侧的表达式一般为 `promise` 对象,但也可以是其它的值
- 如果表达式是 `promise` 对象，`await` 返回的是 `promise` 成功的值
- 如果表达式是其它值，直接将此值作为 `await` 的返回值

## 4.注意

- `await` 必须写在 `async` 函数中，但 `async` 函数中可以没有 `await`
- 如果 `await` 的  `promise` 失败了，就会抛出异常，需要通过 `try..catch` 捕获处理
- 当一个 promise 抛出异常时，要使用 `try...catch` 捕获异常，必须使用 `await` 使回调函数变为异步回调，否则 `try...catch` 无法捕获到错误。

```js
// 正确示例
async function fn1() {
  return new Promise((resolve, reject) => {
    reject('哈哈哈')
  }, 1000)
}
async function fn() {
  try {
    const res = await fn1() // 将 await 去掉，则catch 无法捕获异常
    console.log('成功：' + res)
  } catch (error) {
    console.log('异常：' + error)
  }
}
fn()
// 输出：'异常：哈哈哈'
```