# （四）ECMAScript 8 新特性

## 1. async 和 await

`async` 和 `await` 两种语法结合可以让异步代码像同步代码一样。（即：看起来是同步的，实质上是异步的。）

先从字面意思理解，`async` 意为异步，可以用于声明一个函数前，该函数是异步的。`await` 意为等待，即等待一个异步方法完成。

### 1.1 async 函数

`async` 声明（`function`）的函数成为 async 函数，语法：
```js
async function funcName() {
    //statements 
}
```
`async` 内部可以使用 `await`，也可以不使用。
`async` 函数的返回值是一个 `Promise` 对象，因此执行这个函数时，可以使用 `then` 和 `catch` 方法。
根据 **函数体内部** 的返回值， `async` 函数返回值具体情况如下：
- 函数体内不返回任何值，则 `async` 函数返回值为一个成功（`fulfilled`）的 `Promise` 对象，状态值为 `undefined`。
  ```js
  let a = async function() {}
  let res = a()
  console.log(res)
  // Promise{<fullfilled>: undefined}
  ```
- 返回结果不是一个 `Promise` ，则 `async` 函数返回值为一个成功（`fulfilled`）的 `Promise` 对象，状态值为这个内部返回值。
  ```js
  let a = async function () {
    return 'hello'
  }
  let res = a()
  console.log(res) 
  // Promise{<fullfilled>: 'hello'}
  ```
- 内部抛出错误，则 `async` 函数返回值为一个失败的 `Promise` 对象。
  ```js
  let a = async function foo() {
    throw new Error('出错了')
  }
  a().catch(reason => {
    console.log(reason)
  })
  ```
- 若函数内部返回值是一个 `Promise` 对象，则 `async` 函数返回值的状态取决于这个 `Promise` 对象。
  ```js
  let a = async function () {
    return new Promise((resolve, reject) => {
      resolve("成功")
    })
  }
  a().then(value => {
    console.log(value)
  })
  ```

### 1.2 await

`await` 相当于一个运算符，右边接一个值。一般为一个 `Promise` 对象，也可以是一个非 `Promise` 类型。当右接一个非 `Promise` 类型，`await` 表达式返回的值就是这个值；当右接一个 `Promise` 对象，则 `await` 表达式会阻塞后面的代码，等待当前 `Promise` 对象 `resolve` 的值。

综合 `async` 和 `await` 而言。`await` 必须结合 `async` 使用，而 `async` 则不一定需要 `await`。 `async` 会将其后的函数的返回值封装成一个 `Promise` 对象，而 `await` 会等待这个 `Promise` 完成，然后返回 `resolve` 的结果。当这个 `Promise` 失败或者抛出异常时，需要时使用 `try-catch` 捕获处理。

```js
const p = new Promise((resolve, reject)=>{
  resolve('成功')
})
async function main() {
  let res = await p
  console.log(res)
}
main()
// '成功'
```
```js
const p = new Promise((resolve, reject)=>{
  reject('失败')
})
async function main() {
  try {
    let res = await p
    console.log(res)
  } catch(e) {
    console.log(e)
  }
}
main()
// '失败'
```

### 1.3 打印数字

需求：1s后打印1，接下来2s后打印2，接下来3s后打印3

